# Plan de escenas del vídeo 1. Cada escena: (bloque, frase_ancla o None, tipo, descripción, prompt en inglés sin el estilo)
# tipo: MUSE = clip de vídeo del usuario (Muse) · IMG = imagen generada + movimiento local · GRAF = gráfico hecho en local (gratis)
V = "remote mountain valley in British Columbia, Canada, spring 2022, snow-capped peaks, pine forest, low clouds"
E = [
# 1 INTRO (clips de Muse: ver prompts-video-prueba.md)
(0, None, "MUSE", "Clip 1: Andrew de espaldas en la camioneta, móvil levantado hacia la montaña", "ver prompts-video-prueba.md, clip 1"),
(0, "Se le ve dentro de su camioneta", "MUSE", "Clip 2: la cima con un edificio, a través del parabrisas", "ver prompts-video-prueba.md, clip 2"),
(1, None, "MUSE", "Clip 3: el móvil boca abajo en el asiento, la luz se apaga", "ver prompts-video-prueba.md, clip 3"),
(2, None, "MUSE", "Clip 4: la figura en la cima entre nubes", "ver prompts-video-prueba.md, clip 4"),
(2, "Y desde ese día", "MUSE", "Clip 5: el pueblo de casas de madera al anochecer", "ver prompts-video-prueba.md, clip 5"),
(3, None, "MUSE", "Clip 6: el hombre del camino con los faros", "ver prompts-video-prueba.md, clip 6"),
(3, "Al día siguiente, dos helicópteros", "MUSE", "Clip 7: dos helicópteros con carga colgante", "ver prompts-video-prueba.md, clip 7"),
(3, "Antes del amanecer", "MUSE", "Clip 8: una luz quieta sobre los picos", "ver prompts-video-prueba.md, clip 8"),
(3, "Y una tarde", "MUSE", "Clip 9: la persiana y el auto que se va", "ver prompts-video-prueba.md, clip 9"),
(4, None, "MUSE", "Clip 10: la camioneta vacía en el arcén con niebla", "ver prompts-video-prueba.md, clip 10"),
(5, None, "MUSE", "Clip 11: aproximación a la cima con la torre entre nubes", "ver prompts-video-prueba.md, clip 11"),
(6, None, "MUSE", "Clip 12: el valle al anochecer + título TODOS LO VIERON", "ver prompts-video-prueba.md, clip 12"),
# 2 UN CHICO DE LA ISLA
(7, None, "GRAF", "Tarjeta: «4 de noviembre de 1987 · Columbia Británica, Canadá» sobre un mapa oscuro de Canadá", ""),
(8, None, "IMG", "Campbell River visto desde el agua, con el estrecho y las montañas detrás", "Aerial view of a small coastal town on the east coast of Vancouver Island at grey morning, a strong-current strait of dark water separating the island from snowy mainland mountains, mist"),
(9, None, "MUSE", "Clip 13: el puerto pesquero (ya en prompts-video-prueba.md)", "ver prompts-video-prueba.md, clip 13"),
(9, "Y por detrás, el bosque", "MUSE", "Clip 14: el bosque gigante subiendo hacia las montañas", "ver prompts-video-prueba.md, clip 14"),
(10, None, "IMG", "Foto de familia antigua borrosa sobre una mesa de madera, sin caras reconocibles", "An old faded 1990s family photo print lying on a wooden kitchen table, the photo too blurry and sun-bleached to recognize any faces, rain on the window behind, soft light"),
(11, None, "IMG", "Un niño de espaldas frente a un ordenador antiguo de los 90, en una habitación con lluvia fuera", "A boy seen from behind sitting in front of an old beige 1990s CRT computer in a small bedroom, the screen glowing amber, rain outside the window, pine trees"),
(11, "Y ya era adulto", "IMG", "Manos de adulto sujetando un smartphone, cámara encendida, con bosque detrás", "Close-up of a man's hands holding a smartphone recording a misty forest, the screen glowing amber, no visible interface text"),
(12, None, "IMG", "Una fábrica de celulosa cerrada junto al mar, chimeneas apagadas", "A closed, abandoned pulp mill on the coast of Vancouver Island, cold silent chimneys, rusted metal, empty parking lot, grey rain"),
(12, "si querías un buen sueldo", "IMG", "Un hombre de espaldas cargando una bolsa en una camioneta al amanecer, a punto de irse", "A man in his thirties seen from behind loading a duffel bag into the back of a work pickup truck at dawn in front of a small wooden house, wet road, forest"),
# 3 LA VIDA EN EL VALLE
(14, None, "GRAF", "Mapa animado: de Campbell River a Valemount, ~700 km, entre Rocosas, Monashee y Cariboo", ""),
(15, None, "IMG", "Valemount desde el aire: pueblo pequeño en el fondo del valle, la autopista cruzándolo", f"Aerial view of a tiny village of about a thousand people at the bottom of a narrow valley, a railway station, a gas station, a few motels, a single two-lane highway crossing it north to south, {V}"),
(16, None, "IMG", "La vieja estación de tren de madera de Valemount", "An old small wooden railway station in a mountain village, empty platform, rails disappearing toward snowy peaks, overcast"),
(16, "Durante décadas vivió de la madera", "IMG", "Un aserradero abandonado con pilas de troncos grises", "An abandoned sawmill in a mountain valley, grey weathered log piles, rusted conveyor, snow patches"),
(17, None, "IMG", "Una franja de obra del oleoducto cortando el bosque, tubos enormes alineados", f"A wide pipeline construction right-of-way cut through the pine forest of a {V}, huge steel pipe sections lined up on the ground, yellow excavators"),
(18, None, "IMG", "El campamento de trabajadores: módulos prefabricados iluminados en la nieve", "A large remote work camp of prefabricated modular buildings in a snowy mountain valley at dusk, rows of pickup trucks, floodlights, one amber window"),
(18, "camiones a todas horas", "IMG", "Camiones y maquinaria en un camino forestal, polvo, un control de obra", "Heavy trucks and machinery on a gravel forest road, dust in the air, a construction checkpoint with a barrier, pine trees, mountains"),
(19, None, "IMG", "Un helicóptero posado en un claro con el rotor parado, montañas detrás", "A utility helicopter parked on a gravel landing pad in a forest clearing, rotor still, cargo net on the ground, snowy mountains behind, overcast"),
(20, None, "IMG", "Andrew de espaldas conduciendo por la Yellowhead al amanecer", "A man seen from behind driving a work pickup truck on an empty two-lane mountain highway at dawn, his hands on the wheel, snow-capped mountains ahead"),
(20, "En sus ratos libres", "IMG", "Andrew de espaldas en una habitación sencilla mirando el móvil por la noche", "A man in his thirties seen from behind sitting on the edge of a bed in a plain rented room at night, looking at his smartphone, its amber glow on the wall"),
(21, None, "IMG", "Canoe Mountain desde la autopista: se levanta de golpe sobre el valle", f"A huge steep snow-covered mountain rising abruptly above a valley, seen from a two-lane highway, its summit 1800 meters above the valley floor, {V}"),
(21, "en invierno, allá arriba", "IMG", "La cima en invierno: ventisca, nieve volando sobre la roca", "A bare rocky mountain summit in a winter blizzard, snow blowing violently across the ridge, extreme cold, no people"),
(22, None, "IMG", "Retrovisor de la camioneta con la montaña reflejada", "A pickup truck side mirror reflecting a huge snowy mountain while driving on a mountain highway, motion blur on the trees"),
# 4 NUEVE DE ABRIL
(23, None, "GRAF", "Tarjeta de fecha: «9 de abril de 2022»", ""),
(23, "Por la autopista baja", "IMG", "Una camioneta de trabajo bajando por la autopista, vista desde lejos", f"A single work pickup truck driving down an empty highway seen from far away, {V}"),
(24, None, "MUSE", "El zoom del móvil a la cima: aparece una figura oscura de pie", "A smartphone held up inside a moving truck, its screen showing a heavily zoomed, grainy, pixelated image of a mountain summit with a tiny dark standing figure, handheld shake. Cold desaturated grade, amber phone glow. No text."),
(25, None, "IMG", "Perfil del conductor en silueta, mirando la carretera", "Silhouette of a truck driver in profile against the window, looking at the road, face in deep shadow, mountains blurred outside"),
(26, None, "GRAF", "Gráfico de escala: una persona vs. un edificio a 16 km", ""),
(27, None, "IMG", "El móvil en la oscuridad subiendo un video, pantalla ámbar sin texto legible", "A smartphone on a dark table at night, its screen glowing amber showing an upload progress bar, no readable text, a hand next to it"),
(28, None, "GRAF", "Contador animado: 56.000 → 500.000 seguidores · 4 millones de reproducciones", ""),
(29, None, "IMG", "Mesa de investigador: fotos, mapa topográfico, chinchetas e hilo rojo", "An investigator's desk at night: printed photos of a mountain, a topographic map with pins and red string, a notebook, a desk lamp with amber light"),
(30, None, "IMG", "Silueta de una mujer de espaldas junto a una ventana con lluvia", "Silhouette of a woman seen from behind standing by a rainy window at dusk, mountains outside, face never visible"),
# 5 EL PRIMER VIDEO
(31, None, "IMG", "Un móvil vertical reproduciendo un video tembloroso de la montaña", "A smartphone held vertically playing a shaky video of a snowy mountain, in a dark room, the screen the only light"),
(32, None, "MUSE", "Desde el asiento del copiloto: la montaña por la ventanilla, todo vibra", "From the passenger seat of a moving pickup truck, a huge snowy mountain seen through the side window, the image vibrating with the engine, highway and pine trees passing"),
(33, None, "IMG", "Imagen pixelada: mancha blanca de la cima con un punto oscuro", "Extreme digital zoom of a mountain summit, heavy pixelation and noise, a white smudge of snow with a small dark elongated blob on top"),
(34, None, "GRAF", "La misma imagen con contorno marcado: «hombros, cabeza, piernas»", ""),
(35, None, "IMG", "Interior de la camioneta: dos hombres de espaldas, uno señala", "Inside a moving pickup truck, two men seen from behind, the passenger pointing at a distant mountain, the driver looking at the road"),
(37, None, "GRAF", "Diagrama: 16 km de distancia y 1.800 m de altura, la persona ocuparía menos de un píxel", ""),
(38, None, "IMG", "Un grano de arroz en el borde de una piscina olímpica vacía", "A single grain of rice on the edge of a huge empty Olympic swimming pool, extreme depth of field, cold light"),
(40, None, "GRAF", "Pantalla dividida: «algo enorme» / «no es una persona»", ""),
(42, None, "IMG", "Muchas pantallas de móviles encendidas en la oscuridad", "Dozens of smartphone screens glowing in the dark held by silhouetted people in different rooms, collage, no readable text"),
(43, None, "IMG", "Un pulgar haciendo scroll en comentarios, pantalla desenfocada", "A thumb scrolling on a smartphone screen full of blurred unreadable comments, dark room, amber glow"),
# 6 LA MONTAÑA
(45, None, "IMG", "Canoe Mountain al amanecer, majestuosa, nubes bajo la cima", "A massive mountain at sunrise with clouds below its summit, the protagonist of the landscape, Canadian Rockies, cold light with a thin amber rim"),
(46, None, "IMG", "El monte Robson al fondo, el pico más alto de las Rocosas", "Mount Robson, the highest peak of the Canadian Rockies, a huge glaciated pyramid with a cloud banner, seen from a distant valley, spring"),
(47, None, "IMG", "La cara este: precipicio de 1.000 m cayendo al embalse de Kinbasket", "A sheer thousand-meter cliff falling straight down from a mountain summit into a long cold reservoir lake, aerial view, snow on the ridge"),
(48, None, "IMG", "El camino de tierra subiendo en zigzag por la ladera oeste", "A narrow dirt road switchbacking up a gentler mountain slope toward a high summit, patches of snow, an off-road truck far away"),
(49, None, "IMG", "Final del camino: algo construido en la cima, entre la niebla", "The end of a high mountain dirt road disappearing into fog near a summit, the vague shape of a man-made structure barely visible in the mist"),
(51, None, "IMG", "La cima entre nubes, sin revelar nada", "A mountain summit completely hidden inside a moving cloud, only rock and snow visible below it, ominous"),
# 7 VA Y VIENE
(52, None, "GRAF", "Tarjeta de fecha: «11 de abril de 2022»", ""),
(53, None, "IMG", "Andrew de espaldas en su camioneta grabándose (sin cara)", "A man in his thirties seen from behind in a parked pickup truck holding a phone in selfie mode, his face not visible, snowy mountains through the windshield"),
(55, None, "IMG", "Vista desde la zona del campamento: la montaña más cerca", "A large snowy mountain seen from a pipeline work camp area southeast of a village, modular buildings in the foreground, closer view of the summit"),
(56, None, "MUSE", "Zoom a la cima vacía: la figura ya no está", "Shaky smartphone zoom toward a snowy mountain summit that is completely empty, only snow, rock and sky, handheld, grainy"),
(58, None, "IMG", "Dos siluetas hablando en la barra de un bar de pueblo", "Two silhouetted men talking at the bar of a small-town mountain pub at night, a single amber lamp, faces never visible"),
(59, None, "IMG", "Una persona en la cama a las 2 de la madrugada mirando el móvil", "A person lying in bed at 2 a.m. in a dark room, face hidden, lit only by the amber glow of a smartphone"),
(61, None, "IMG", "Un camino forestal que sube hacia la montaña al atardecer", "A gravel forest service road climbing into a dark pine forest toward a mountain at dusk, a closed gate in the distance"),
# 8 EL HOMBRE DEL CAMINO
(62, None, "IMG", "Interior de una casa modesta, un móvil en un trípode apuntando a una silla vacía", "Interior of a modest small-town house at night, a phone on a small tripod pointed at an empty chair, a lamp, blinds closed"),
(63, None, "IMG", "Camino forestal de grava: un hombre de pie a lo lejos bloqueando el paso", "A gravel forest road between tall pines, a man standing far away in the middle of the road blocking it, seen from a truck windshield, overcast"),
(64, None, "IMG", "Una cadena con un candado y un cartel sin texto cerrando el camino", "A metal chain and padlock across a gravel forest road with a blank weathered sign, pine forest, mud and snow"),
(65, None, "IMG", "Silueta de un hombre con gafas oscuras junto a un sedán negro", "Silhouette of a man in a dark jacket and sunglasses standing next to a black sedan on a forest road, backlit, face hidden"),
(66, None, "IMG", "Montaje conspiranoico: archivos, fotos, una lámpara", "A dark room with conspiracy files, grainy surveillance photos of a mountain and a car spread on a table, a single amber desk lamp"),
(67, None, "IMG", "Un televisor antiguo encendido en una sala oscura", "An old television glowing in a dark living room showing a blurry night scene, no readable text, silhouette of a viewer"),
(68, None, "IMG", "La camioneta saliendo de noche, faros encendidos", "A pickup truck leaving a small wooden house before dawn, headlights on, exhaust in cold air, dark mountains"),
# 9 EL DÍA DE LOS CUATRO VIDEOS
(69, None, "GRAF", "Tarjeta de fecha: «13 de abril de 2022 · 4 videos»", ""),
(70, None, "MUSE", "5:30 h, noche: la camioneta arranca, faros en la niebla", "5:30 a.m., still dark, a pickup truck starting up in front of a small house, headlights cutting through fog, exhaust in the cold air, a mountain village"),
(71, None, "MUSE", "La luz brillante y quieta sobre los picos (desde la camioneta)", "From inside a parked pickup truck before dawn, a bright white light hovering perfectly still above dark mountain peaks, seen through the windshield, phone held up recording it"),
(72, None, "IMG", "Un reproductor de música antiguo y un estrellado cielo nocturno", "A smartphone lying on a truck dashboard under a starry pre-dawn sky over mountains, the screen glowing, an eerie atmosphere"),
(73, None, "IMG", "Una luz subiendo entre las estrellas sobre las montañas", "A small light rising into a starry sky above jagged mountain peaks, long exposure feel, deep blue night"),
(75, None, "IMG", "El cielo de madrugada con un punto brillante, sin explicación", "A pre-dawn eastern sky over snowy peaks with one very bright point of light, a faint glow on the horizon"),
(76, None, "MUSE", "Dos helicópteros con una carga colgando de un cable, vistos desde la camioneta", "Two helicopters flying over a mountain valley seen from a moving truck window, one carrying a load swinging on a long cable"),
(79, None, "MUSE", "Noche, camino forestal: los faros iluminan un sedán negro y un hombre caminando", "Night, a gravel forest road, truck headlights reveal a black sedan parked ahead and a man walking in front of it, dust in the beams, face hidden"),
(80, None, "IMG", "Imagen casi negra: un móvil boca abajo en el salpicadero, la luz de los faros", "Almost black frame: a phone lying face down on a truck dashboard at night, faint headlight glow on the windshield"),
(81, None, "GRAF", "Ondas de audio sobre negro con la frase subtitulada «La carretera está cerrada. Date la vuelta.»", ""),
(83, None, "IMG", "La camioneta dando la vuelta en el camino, luces traseras rojas", "A pickup truck turning around on a narrow gravel forest road at night, red tail lights glowing, dust"),
(84, None, "IMG", "Un hombre de espaldas en el camino, mano en alto, gesto tranquilo", "A man seen from behind standing calmly on a forest road at night with one hand raised in a polite stop gesture, headlights lighting him, no badge, no weapon"),
# 10 ME ESTÁN SIGUIENDO
(85, None, "GRAF", "Tarjeta de fecha: «16 de abril de 2022»", ""),
(86, None, "MUSE", "La persiana entreabierta: fuera, un auto parado", "Fingers parting the slats of a window blind in a dark room, outside a dark sedan parked on an empty small-town street with a snowy mountain behind"),
(87, None, "IMG", "Un hombre sale a la puerta de casa, el auto se aleja", "A man seen from behind stepping out the front door of a small wooden house onto a gravel street as a dark car speeds away, tail lights"),
(89, None, "IMG", "La casa de noche vista desde la calle, una ventana iluminada", "A small wooden house at night seen from across an empty street, one amber lit window, mountains in the dark, a feeling of being watched"),
(90, None, "IMG", "Mensajes de preocupación: muchos móviles encendidos en la oscuridad", "Many hands holding glowing smartphones in the dark, worried silhouettes, unreadable blurred messages"),
(91, None, "IMG", "La camioneta aparcada y cubierta de escarcha, días sin moverse", "A pickup truck parked and covered in frost in front of a small house, untouched for days, quiet morning"),
(93, None, "GRAF", "Mapa: el punto del video y, a 20 km, Mica Mountain · 1955", ""),
# 11 INTERNET HACE LO SUYO
(95, None, "IMG", "Una red de pantallas conectadas por líneas, el caso se propaga", "Abstract network of glowing phone screens connected by lines of light spreading across a dark map of the world"),
(98, None, "IMG", "Collage oscuro de teorías: sombra de bigfoot, ovni, gigantes antiguos", "A dark collage of mystery theories: the shadow of a hairy giant in a forest, a UFO light in the sky, an ancient engraving of giants, old paper texture, no readable text"),
(99, None, "IMG", "Fotos antiguas, mapas y recortes sobre una mesa", "Old photographs, maps and newspaper clippings with unreadable text scattered on a dark table under a lamp"),
(101, None, "IMG", "Una antena vieja en una cima: la foto que nadie comparte", "An old microwave relay antenna on a mountain summit on a clear grey day, boring and plain, documentary photo"),
(102, None, "GRAF", "Calendario: los días pasan, 10, 15, 20", ""),
(103, None, "IMG", "Una cuenta congelada: el móvil en una mesa, sin notificaciones", "A smartphone on a table in an empty room, screen dark, dust in a beam of light, silence"),
# 12 TODO ERA FALSO
(105, None, "GRAF", "Tarjeta de fecha: «6 de mayo de 2022»", ""),
(106, None, "IMG", "Un hombre de espaldas hablando a un móvil en un trípode", "A man in his thirties seen from behind sitting in front of a phone on a tripod in a dim room, recording himself, his face not visible"),
(107, None, "GRAF", "Repaso rápido: gigante, hombre del camino, helicópteros, auto, tachados", ""),
(110, None, "IMG", "Una mirada hacia fuera del encuadre: una puerta entreabierta en la oscuridad", "A dim room with a door slightly ajar in the background, a sliver of light, the feeling that someone is just out of frame"),
(112, None, "IMG", "Una confesión firmada que arde lentamente", "A handwritten page of a confession slowly burning at the edges on a dark table, smoke, unreadable text"),
# 13 LOS DOS ÚLTIMOS VIDEOS
(115, None, "GRAF", "Tarjeta de fecha: «16 de mayo de 2022 · Tengo miedo»", ""),
(116, None, "MUSE", "Pasillo de casa casi a oscuras, cámara en mano caminando deprisa", "Handheld first-person view walking quickly down a very dark narrow hallway of a small house, a single amber light at the end, shaky, tense"),
(118, None, "IMG", "Silueta de un hombre sentado en el suelo junto a la ventana", "Silhouette of a man sitting on the floor against a wall under a window at night, knees up, head down, blue moonlight"),
(119, None, "GRAF", "Tarjeta de fecha: «17 de mayo de 2022 · el último video»", ""),
(120, None, "MUSE", "Zoom a la cima de otra montaña: un edificio con forma de caja y ventanas", "Smartphone zoom from a truck toward a mountain summit with a box-shaped building with large windows sitting on top of the rock, grainy, handheld"),
(122, None, "IMG", "La gente imagina una base secreta en la cumbre", "Speculative illustration of a secret base built into a mountain summit at night, lights in the windows, fog, ominous"),
(124, None, "IMG", "La pantalla del perfil congelada, el móvil cubierto de polvo", "An abandoned smartphone on a windowsill covered in dust, a mountain outside the window, time passing, cold light"),
(125, None, "IMG", "El edificio de la cima a lo lejos, entre nubes", "A distant summit building between clouds on a high mountain, small and real, cold daylight"),
# 14 UNO DE JULIO
(127, None, "IMG", "Día de Canadá en un pueblo: banderas y fuegos artificiales sobre las montañas", "Canada Day night in a small mountain town: fireworks over the dark mountains, small red flags on houses, the celebration feeling distant and cold"),
(128, None, "GRAF", "Tarjeta: «Andrew Ryan Watchorn Dawson · 1987 – 2022»", ""),
(129, None, "IMG", "Un periódico local doblado sobre una mesa, una vela", "A folded small-town local newspaper on a wooden table next to a lit candle, the text unreadable, soft amber flame"),
(131, None, "IMG", "Un tablero de piezas de rompecabezas oscuras", "Dark puzzle pieces scattered on a table, several missing, a single lamp"),
(133, None, "IMG", "Dos sombras opuestas proyectadas por la misma lámpara", "One lamp in a dark room casting two opposite shadows of the same man on two walls, symbolic"),
(136, None, "IMG", "El camino hacia la montaña, de día, dispuesto a subir", "A dirt road leading up toward a big mountain in daylight, the clouds lifting, a sense of setting off to find the truth"),
# 15 A VEINTE KILÓMETROS, 1955
(138, None, "GRAF", "Tarjeta de fecha: «Octubre de 1955 · Tête Jaune Cache»", ""),
(139, None, "IMG", "Un trampero de los años 50 de espaldas con su rifle en el bosque", "A 1950s trapper and hunter seen from behind walking through an autumn mountain forest with a rifle and a backpack, sepia-tinted cold grade"),
(140, None, "IMG", "Una vieja mina abandonada en Mica Mountain", "The entrance of an old abandoned mine on a forested mountainside, rotten wooden beams, autumn, 1950s feeling"),
(141, None, "IMG", "Un claro de bosque al sol de la tarde, algo se mueve en los arbustos", "A small sunny clearing in an autumn mountain forest, late afternoon light, the bushes moving as if something large is behind them"),
(142, None, "MUSE", "Una figura enorme y peluda se pone de pie entre los arbustos (lejos, borrosa)", "Far away in an autumn forest clearing, a large dark hairy figure slowly stands up on two legs from the bushes, blurry, partially hidden, 1950s film look"),
(143, None, "IMG", "Silueta peluda de casi dos metros en el bosque, desenfocada", "A blurry silhouette of a tall hairy upright creature among trees at the edge of a clearing, silver-tipped brown hair catching the light, out of focus, eerie"),
(144, None, "IMG", "La figura se aleja caminando hacia los árboles", "A blurry tall hairy figure walking away upright into a dark forest, seen from behind, unhurried"),
(146, None, "IMG", "Una declaración jurada de 1957 con una firma y un sello", "A 1950s typewritten sworn statement on old paper with an ink signature and an embossed seal, text unreadable, lamp light"),
(148, None, "IMG", "Una huella grande en el barro, sin escala clara", "A large footprint in mud on a forest trail, ambiguous, cold light, documentary photo"),
(150, None, "IMG", "Costa de Columbia Británica: bosque y canoas tradicionales en la niebla", "The misty Pacific coast of British Columbia with dense rainforest, traditional carved wooden canoes on a pebble beach, respectful documentary style"),
(151, None, "IMG", "Hoguera en el bosque de noche: historias que pasan de generación en generación", "A campfire in a dark mountain forest at night, sparks rising, silhouettes of people sitting around listening, faces hidden"),
# 16 LA FOTO QUE ALGUIEN ROBÓ
(153, None, "IMG", "Un archivo antiguo con cajas y documentos", "A dusty old archive room with shelves of boxes and folders, a beam of light through a window"),
(154, None, "IMG", "Una foto antigua: un animal peludo en la nieve y unas raquetas clavadas", "An antique 1890s sepia photograph showing a hairy animal lying in the snow in a mountain clearing with a trap on one limb and a pair of snowshoes standing upright beside it"),
(155, None, "IMG", "El reverso de la foto con una nota manuscrita ilegible", "The back of an antique photograph with an old handwritten note in faded ink, unreadable, on a dark desk"),
(155, "se había metido en la oficina", "IMG", "Una mano copiando fotos a escondidas en una oficina antigua de noche", "A hand secretly taking photos out of a filing cabinet in a dark 19th-century office at night, a candle"),
(156, None, "GRAF", "Esquema: hallazgo → organización que lo esconde → hombre corriente", ""),
(157, None, "IMG", "Lupa sobre la foto antigua: análisis", "A magnifying glass over an antique sepia photograph on an investigator's desk, analysis, lamp light"),
(158, None, "IMG", "Humo que forma figuras sobre un fondo oscuro: la leyenda ya existía", "Smoke curling in a dark space forming vague shapes of figures, symbolic, cold light"),
# 17 UNA PELÍCULA EN UN RÍO DE CALIFORNIA
(159, None, "IMG", "Un proyector de cine de 16 mm encendido en una sala oscura", "A 16mm film projector running in a dark room, its beam of light full of dust, warm amber lamp"),
(160, None, "GRAF", "Tarjeta de fecha: «20 de octubre de 1967 · Bluff Creek, California»", ""),
(160, "dos hombres a caballo", "IMG", "Dos jinetes recorriendo el cauce de un riachuelo en el bosque, años 60", "Two horsemen riding along a rocky creek bed in a dense northern California forest in 1967, seen from behind, autumn"),
(161, None, "MUSE", "Imagen de película antigua temblorosa: una figura oscura camina junto al río", "Shaky 16mm 1960s film footage feel: a large dark figure walking on two legs along a creek bank toward the trees, film scratches, jumpy framing, distant and blurry"),
(163, None, "IMG", "Una sala de análisis con fotogramas proyectados", "A dim analysis room with blurry film frames projected on a wall, silhouettes of researchers"),
(164, None, "GRAF", "El patrón: película de 1967 y video de 2022, lado a lado (recreaciones)", ""),
(166, None, "IMG", "Medición sobre el terreno: un trípode y un teodolito frente a la montaña", "A surveyor's tripod and theodolite set up on a roadside facing a big snowy mountain, measuring, overcast"),
# 18 LO QUE HAY EN LA CIMA
(168, None, "IMG", "Subiendo por el camino de tierra de la ladera oeste", "Point of view driving up a high dirt mountain road with steep drop-offs and patches of snow, the summit ahead"),
(169, None, "MUSE", "Revelación: en la cima, una torre de microondas y un edificio de hormigón", "Slow reveal over a mountain ridge: on the summit stands an old microwave relay tower with dish antennas and a small concrete and metal building, clouds passing, wind"),
(170, None, "IMG", "Canadá en los años 50: una torre de microondas en una colina", "1950s Canada: a newly built microwave relay tower on a hilltop, workers far away, archival photo feel"),
(171, None, "GRAF", "Mapa: 139 torres de costa a costa, más de 6.000 km (1958)", ""),
(172, None, "IMG", "Una cadena de torres en las cimas, de colina en colina", "A chain of microwave relay towers on successive mountain summits receding into the distance, line of sight, dusk"),
(173, None, "IMG", "Cables de fibra óptica brillando frente a una antena oxidada", "Glowing fiber optic cables in the foreground with a rusted old antenna out of focus behind, obsolescence"),
(174, None, "IMG", "La estación abandonada: puerta forzada, grafitis, basura, precipicio", "An abandoned concrete relay building on a mountain summit with a forced door, broken windows, graffiti, debris, a thousand-meter cliff just behind it"),
(176, None, "GRAF", "Comparación: el fotograma pixelado y la torre con el mismo zoom", ""),
(177, None, "IMG", "La torre vista desde muy lejos, borrosa: parece una figura de pie", "A microwave tower on a distant summit seen through heavy haze and digital zoom, blurry, looking like a tall standing figure with shoulders"),
(179, None, "IMG", "Un hombre de espaldas en el arcén mirando la cima tapada por nubes", "A man seen from behind standing by a highway shoulder looking up at a mountain whose summit is completely hidden by clouds"),
(180, None, "IMG", "Nubes bajas que tapan y destapan la cima", "Low clouds drifting across a mountain summit, half covering and revealing it, spring"),
(181, None, "IMG", "La antena vieja, tranquila, al atardecer: la respuesta aburrida", "An old antenna tower on a mountain summit at calm sunset, plain and peaceful, a single amber glow"),
# 19 EL HOMBRE, LOS HELICÓPTEROS Y LA LUZ
(183, None, "IMG", "El camino forestal de día: un vigilante de obra con chaleco", "A construction security guard in a high-visibility vest seen from behind at a gravel road checkpoint in a pine forest, daylight"),
(185, None, "IMG", "Obras del oleoducto: maquinaria, voladuras, zona restringida", "Pipeline construction zone in a mountain forest: excavators, a blasting area with orange fencing, restricted access barrier, dust"),
(186, None, "IMG", "Dos amigos de espaldas junto a una camioneta riéndose", "Two men seen from behind leaning on a pickup truck in a mountain village, casual, relaxed body language"),
(187, None, "IMG", "Un helicóptero llevando tubos colgando hacia la obra", "A utility helicopter carrying steel pipe sections on a long cable over a forested mountain toward a construction site"),
(190, None, "IMG", "El cielo antes del amanecer sobre las montañas", "The pre-dawn sky over mountain peaks, deep blue fading to teal, a few bright points of light"),
(192, None, "GRAF", "Mapa del cielo: Venus, Júpiter, Marte y Saturno al este, abril de 2022", ""),
(193, None, "IMG", "Venus muy brillante sobre los picos, quieto", "Venus shining extremely bright and still above jagged snowy mountain peaks before dawn, a faint glow on the horizon"),
(195, None, "IMG", "Un observador de espaldas mirando el lucero del alba", "Silhouette of a person seen from behind looking at a single very bright star above the mountains before dawn"),
(196, None, "IMG", "Una mesa de edición: auriculares y una línea de tiempo", "A video editing setup at night: headphones, a laptop with an editing timeline of colored blocks, no readable text, amber lamp"),
# 20 EL EDIFICIO QUE NO ESTABA AHÍ
(198, None, "IMG", "El edificio de caja con ventanas en la cumbre, entre nubes", "A box-shaped building with large windows on a rocky mountain summit, clouds passing, seen from far below"),
(200, None, "GRAF", "Mapa: Valemount → Jasper, una hora al este, Alberta", ""),
(201, None, "IMG", "The Whistlers: la estación de arriba del teleférico en la roca", "A cable car upper station with large windows sitting on a rocky summit at 2263 meters above a mountain town, cable lines descending, no logos"),
(202, None, "IMG", "Una cabina de teleférico subiendo con turistas", "A red cable car cabin gliding up toward a mountain summit station, tourists inside as small silhouettes, no logos"),
(203, None, "IMG", "Desde las calles de un pueblo de montaña: la estación en la cima al fondo", "View from the street of a small mountain tourist town toward a peak with a small station building on top, cold evening"),
(205, None, "IMG", "La autopista entre Valemount y Jasper", "An empty highway winding between huge Rocky Mountains toward a distant mountain town, spring"),
(206, None, "IMG", "Un móvil grabando, el dedo a punto de pulsar «publicar»", "A thumb hovering over the upload button of a smartphone at night, screen glowing amber, no readable text"),
# 21 POR QUÉ TODOS LO CREÍMOS
(207, None, "IMG", "Millones de luces de pantallas en una ciudad de noche", "A night city seen from above with thousands of tiny glowing windows and phone screens, symbolic of millions of viewers"),
(209, None, "IMG", "Una cara en las nubes, una persona en las sombras (pareidolia)", "Clouds over a mountain that accidentally form the shape of a face, pareidolia, subtle, cold light"),
(210, None, "IMG", "Una cámara de vídeo caída en un bosque oscuro", "An old handheld video camera lying on leaves in a dark forest, red record light on, found-footage feeling"),
(210, "Diez años después", "IMG", "Silueta muy alta y delgada al final de un bosque, desenfocada", "A very tall thin faceless silhouette standing far away between bare trees in fog, blurry, internet legend feeling"),
(211, None, "IMG", "Una puerta que se cierra en un pasillo oscuro: sin final", "A door slowly closing at the end of a dark corridor, a sliver of light disappearing"),
(213, None, "GRAF", "Dos fechas iguales: «1 de julio de 1958» y «1 de julio de 2022»", ""),
(215, None, "IMG", "Dos hilos que se cruzan en un tablero sin relación real", "Two red strings crossing on a corkboard between unrelated photos, symbolic of false connections, lamp light"),
(216, None, "GRAF", "Contador: 600.000 reproducciones en 4 días (dic. 2022)", ""),
# 22 LO QUE CONTÓ QUIEN MEJOR LO CONOCÍA
(218, None, "IMG", "Silueta de una mujer de espaldas sentada frente a un móvil", "A woman seen from behind sitting on a sofa in a dim living room, holding a phone, a soft lamp, her face never visible"),
(220, None, "IMG", "Ventana con lluvia y una taza de café junto a ella", "A rainy window at grey morning with a cup of coffee on the sill, quiet sadness, soft cold light"),
(222, None, "IMG", "Un solo móvil encendido en una mesa vacía: pocas visitas", "A single phone glowing on an empty table in a large dark room, loneliness"),
(224, None, "IMG", "Manos sujetando una foto boca abajo", "Hands holding a photograph face down on a lap, a wedding ring, soft window light"),
(225, None, "IMG", "La montaña al amanecer, despejada, con la antena en la cima", "A clear sunrise over the mountain with the old antenna visible on its summit, calm, the fog gone"),
(226, None, "IMG", "La camioneta aparcada frente al lago al atardecer, vacía", "An empty work pickup truck parked by a calm mountain lake at sunset, a single amber reflection, peaceful and sad"),
# 23 LO QUE NADIE TE CONTÓ
(227, None, "IMG", "El valle entero desde la cima, inmenso", "Wide view of the whole valley from a mountain summit, the tiny village far below, immense and silent"),
(228, None, "IMG", "Una persona sola en un banco mirando la montaña", "A person seen from behind sitting alone on a wooden bench looking at a big mountain at dusk"),
(229, None, "IMG", "La cima a plena luz: la respuesta estaba a la vista", "A mountain summit in full clear daylight, every detail visible, an old antenna on top, honest and simple"),
(230, None, "GRAF", "Tarjeta de ayuda: «¿Lo estás pasando mal? España: 024 · Otros países: en la descripción»", ""),
(231, None, "GRAF", "Tarjeta en memoria: «En memoria de Andrew Dawson (1987 – 2022)» sobre la montaña al amanecer", ""),
# 24 CIERRE
(232, None, "GRAF", "Logo y lema del canal: TODOS LO VIERON · la historia real detrás del misterio", ""),
(233, None, "IMG", "Una mesa de investigación con varios expedientes cerrados", "An investigator's desk with several closed case folders stacked, a lamp, a map, ready for the next story"),
(234, None, "GRAF", "Botón de suscribirse animado + campanita (sin logo de YouTube)", ""),
(235, None, "IMG", "Un camino que se pierde en la niebla del bosque: el próximo misterio", "A forest path disappearing into thick fog, an amber light far away at the end, inviting"),
(236, None, "GRAF", "Pantalla final: «Nos vemos en el próximo capítulo de misterio» + fundido", ""),
]
